acme_data:
    resource: "@AcmeDataBundle/Controller/"
    type:     annotation
    prefix:   /

acme_main:
    resource: "@AcmeMainBundle/Controller/"
    type:     annotation
    prefix:   /

acme_admin:
    resource: "@AcmeAdminBundle/Controller/"
    type:     annotation
    prefix:   /

acme_try:
    resource: "@AcmeTryBundle/Controller/"
    type:     annotation
    prefix:   /

acme_test:
    resource: "@AcmeTestBundle/Resources/config/routing.yml"
    prefix:   /

acme_user:
    resource: "@AcmeUserBundle/Controller/"
    type:      annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
 
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    

